### ISSUE TITLE
ios真机运行是报错 dyld`dyld_fatal_error:

### ISSUE THREAD

**Issue by jinker** [njleonzhang/cordova-baidu-yingyan#1]
dyld`dyld_fatal_error:
->  0x120011088 <+0>: brk    #0x3

xcode：Version 7.3.1 (7D1014)

**Comment by njleonzhang** [comment]
@jinker  reademe里有写哦，

`这个plugin里包的是百度鹰眼的ios开发版SDK，只能用于开发，不能上架。 如需上加请下载上架版。
`
真机上运行的话，请换release版本试试。

**Comment by jinker** [comment]
不是sdk版本的问题，试过换release版本，会有一样的问题

好像是link问题，我换成以下配置就好了
![image](https://cloud.githubusercontent.com/assets/1707634/17044698/053e9414-4ff5-11e6-8da6-412c8f937466.png)

**Comment by njleonzhang** [comment]
@jinker 啊，我是按照百度的要求做的嵌入library。难道他们最近又改了？我建议里可以去百度鹰眼的论坛里发帖问一下。

http://bbs.lbsyun.baidu.com/forum.php?mod=forumdisplay&fid=26

或者等我有空我来研究下 :)
感谢你关注这个小小的plugin

**Comment by njleonzhang** [comment]
这个问题是由于我这个plugin的library嵌入功能没做好，现在的版本应该可以了，关闭这个问题。
