### ISSUE TITLE
添加这个插件报错，不知道是什么原因

### ISSUE THREAD

**Issue by j5272000** [njleonzhang/cordova-baidu-yingyan#10]
![image](https://user-images.githubusercontent.com/39423761/69129489-6bc5bc00-0ae9-11ea-876f-1cfa6a5f5330.png)

cordova版本：7.1.0

SDK已经是百度官网最新的：百度鹰眼轨迹iOS SDK V3.1.1 开发包

**Comment by njleonzhang** [comment]
新版本的 api 有可能改变了吧。这个库不再维护了。
