### ISSUE TITLE
能在后台运行么？

### ISSUE THREAD

**Issue by Yunnying** [njleonzhang/cordova-baidu-yingyan#2]
当app被用户操作为后台以后，比如最小化、关闭屏幕、主动退出（上划移除或者被清理掉）以后，还能获取位置并上传么？

**Comment by njleonzhang** [comment]
哎呀，我做这个plugin的时候，做过测试，但是现在不记得了，建议您可以自己测试下。这些都是百度SDK的行为，建议去百度鹰眼论坛问一下。

**Comment by Yunnying** [comment]
好的。非常感谢啦~
