### ISSUE TITLE
这个直接放在项目中的plugins里面就可以直接使用吗？

### ISSUE THREAD

**Issue by xiaowangshu** [njleonzhang/cordova-baidu-yingyan#3]
在Wex5论坛和百度鹰眼论坛都看到这个例子，由于最近公司需求，所以我把这个例子直接拿过来用，但是出现了好多问题，请问你是用Wex5的什么版本开发的，还有那个依赖插件cordova-plugin-settings-hook是在哪里下载的？可以的话可以给我你的qq或者微信，能不能教我怎么弄，刚接触这个东西，搞了好久。。

**Comment by njleonzhang** [comment]
@xiaowangshu 不好意思  才看到。 你看readme去安装插件，应该可以使用啊，cordova-plugin-settings-hook是会自动安装的。我们的项目里已经在使用了。

**Comment by xiaowangshu** [comment]
没事的，不过我用不了，打包后他会用npm http GET http://registry.cordova.io/cordova-plugin-settings-hook去自动下载，但是请求超时，就是下载不了，不知道有什么解决办法吗？谢谢哈

**Comment by xiaowangshu** [comment]
没事的，不过我用不了，打包后他会用npm http GET http://registry.cordova.io/cordova-plugin-settings-hook去自动下载，但是请求超时，就是下载不了，不知道有什么解决办法吗？谢谢哈

**Comment by njleonzhang** [comment]
https://www.npmjs.com/package/cordova-plugin-settings-hook

```
npm i cordova-plugin-settings-hook
```

你需要翻墙。。。。或者使用淘宝的npm镜像。
```
https://npm.taobao.org/
```

**Comment by xiaowangshu** [comment]
我在https://www.npmjs.com/package/cordova-plugin-settings-hook下载了，然后放到wex5的plugins下，然后打包，还是会去npm http GET http://registry.cordova.io/cordova-plugin-settings-hook请求下载，请问这个地址可以在你的代码中修改吗？

**Comment by njleonzhang** [comment]
你不需要做这些操作的，你这所谓的wex5项目其实应该就是一个cordova项目。wex5其实应该就是一个类似ionic的前端层的封装。

你按照我的readme来，在你项目的根目录下执行
```
cordova plugin add cordova-baidu-yingya
```
看看发生什么错误，如果报超时错误，请翻墙。
然后，按照文档里的说法，配置config.xml
应该不会有问题，如果正有问题，就贴出来，我可以帮你看看。

好像你对cordova的基本概念还不清楚，建议先学习。
仔细读下readme吧：https://github.com/njleonzhang/cordova-baidu-yingyan

**Comment by xiaowangshu** [comment]
感觉Wex5和Android的cordova插件有区别，他使用cordova插件的时候没有config.xml的，打包的时候根据引入语句引入该插件，打包完成后才有config.xml文件，但是这个时候配置重新打包就不行了
开始......
保存配置信息:
编译UI资源: 
清除编译环境:
复制模版工程:
复制工程:
复制插件:
加密UI资源:
更新工程信息:
增加插件:
   使用到的插件: [org.apache.cordova.splashscreen, org.apache.cordova.splashscreen, me.apla.cordova.plugin.app.preferences, cordova-baidu-yingyan, cordova-plugin-settings-hook]
   开始准备插件参数......
   插件参数准备完成
   开始安装插件......
   Installing "org.apache.cordova.splashscreen" for android
   Installing "org.apache.cordova.splashscreen" for ios
   Installing "me.apla.cordova.plugin.app.preferences" for android
   Installing "me.apla.cordova.plugin.app.preferences" for ios
   Installing "cordova-baidu-yingyan" for android
   Fetching plugin "cordova-plugin-settings-hook" via plugin registry
   npm http GET http://registry.cordova.io/cordova-plugin-settings-hook
   npm http GET http://registry.cordova.io/cordova-plugin-settings-hook
   npm http GET http://registry.cordova.io/cordova-plugin-settings-hook
   Failed to install 'cordova-baidu-yingyan':Error: connect ETIMEDOUT
       at errnoException (net.js:904:11)
       at Object.afterConnect [as oncomplete] (net.js:895:19)
****ERROR****: 子任务 "addPlugins" 执行失败。
****ERROR****: 任务 "addPlugins" 执行失败。
****ERROR****: 执行出错：
****ERROR****: 错误信息: addPlugins returned: 1
****ERROR****: 如不能确定具体问题，可参考常见问题: http://wex5.com/cn/bbs/thread-82002-1-1.html

**Comment by njleonzhang** [comment]
没有`config.xml`的话感觉就用不了了， 你可能需要改一改这个plugin的代码了。
你的plugin列表里有cordova-plugin-settings-hook，这个是不需要的，cordova-baidu-yingyan的依赖自己会处理的，不需要你自己加。
我试了一下 ，是OK的。
```
Adding android project...


Creating Cordova project for the Android platform:

	Path: platforms/android
	Package: com.test.test
	Name: gulpIonic


	Activity: MainActivity
	Android target: android-23

Android project created with cordova-android@5.2.2


Installing "cordova-baidu-yingyan" for android


Fetching plugin "cordova-plugin-settings-hook" via npm

Installing "cordova-plugin-settings-hook" for android
```

你也可以看下代码，自己改一改，不然的话你的项目里估计是用不了的。
