### ISSUE TITLE
在ios上部署运行白屏

### ISSUE THREAD

**Issue by fs-danaus** [njleonzhang/cordova-baidu-yingyan#4]
你好，我用xcode8.2打包到真机(ios9.3.5)测试，打开就只是白屏停在那里了，不知是什么原因？在android上打包能正常运行的

**Comment by njleonzhang** [comment]
@fs-danaus 你看xcode console里面应该有报错吧，你具体看看呢

**Comment by fs-danaus** [comment]
我试了直接在
cordova.baiduTrace.setInterval(2, 10).then(function() {
          console.log('setInterval OK');
      });
上面打印一个alert(cordova.baiduTrace)也是没执行到，感觉就是停在那里不动了

**Comment by njleonzhang** [comment]
@fs-danaus 你说的不清楚啊  我没办法帮你想办法啊。
你是说setInterval导致你的程序卡住了么？
你在xcode看下有没有报错？

**Comment by fs-danaus** [comment]
我重新新建了一个来测试，现在是没有白屏了，但 在启动时我用alert(cordova.baiduTrace)，调试时显示undefined。不知是不是有什么地方还没有设置好?

**Comment by fs-danaus** [comment]
忘记说明，我是在旧项目里把插件的相关文件copy到新项目上面的，不是通过 ionic build ios 这样加，会不会是这个原因？

**Comment by njleonzhang** [comment]
@fs-danaus 最好用命令安装，因为我为了方便大家使用，在命令里加了一些脚本，做了一些配置工作。具体你可以看下代码。

**Comment by fs-danaus** [comment]
好的，谢了。




------------------ 原始邮件 ------------------
发件人: "Leon Zhang";<notifications@github.com>;
发送时间: 2016年12月26日(星期一) 上午9:18
收件人: "njleonzhang/cordova-baidu-yingyan"<cordova-baidu-yingyan@noreply.github.com>; 
抄送: "Danaus"<danaus314@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [njleonzhang/cordova-baidu-yingyan] 在ios上部署运行白屏 (#4)




@fs-danaus 最好用命令安装，因为我为了方便大家使用，在命令里加了一些脚本，做了一些配置工作。具体你可以看下代码。

**Comment by njleonzhang** [comment]
@fs-danaus 好用的话 给个star啊  :)

**Comment by fs-danaus** [comment]
hi,


1，已给star :)


2，有个问题想请教下，现在可以调用这个插件定时上传位置到百度服务器了，下一步是如何把这些数据下载到app里再用地图显示出整个轨迹呢？


我大概可以想到这里有二个步骤，第一个是下载，可以用鹰眼SDK的轨迹查询接口来下载，这个接口好像插件还没实现，是吗？，或者用web api提供的应该也是可行。现在我有些不太明白的是用什么接口来显示地图且把整个轨迹画出来？需要用到哪些东东






------------------ 原始邮件 ------------------
发件人: "Leon Zhang";<notifications@github.com>;
发送时间: 2016年12月26日(星期一) 下午2:55
收件人: "njleonzhang/cordova-baidu-yingyan"<cordova-baidu-yingyan@noreply.github.com>; 
抄送: "Danaus"<danaus314@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [njleonzhang/cordova-baidu-yingyan] 在ios上部署运行白屏 (#4)




@fs-danaus 好用的话 给个star啊  :)

**Comment by njleonzhang** [comment]
@fs-danaus 百度提供的app demo里，是有画地图的逻辑的，你可以参考下。现成的代码直接抄
